name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: macos-latest
    
    permissions:
     contents: write
     id-token: write
     packages: write
     actions: write
     pull-requests: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest
    - name: Build and test
      run: |
        xcodebuild -scheme MovieFinder build test -allowProvisioningUpdates


